version: '2'
services:
  redis:
    image: redis
    ports:
     - "6379:6379"
    command: redis-server --bind 0.0.0.0

  mongo:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - mongodata:/data

  rqdashboard:
    build:
      context: .
      dockerfile: Dockerfile-rqdashboard
    ports:
     - "9181:9181"
    depends_on:
     - redis
    links:
     - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    working_dir: /home/enuser/
    depends_on:
      - redis
      - mongo
      - main
    links:
     - redis
     - mongo
     - main
    volumes:
    - endata:/endata
    - ./enCount:/home/enuser/enCount

  main:
    build:
      context: .
      dockerfile: Dockerfile-main
    volumes:
      - endata:/endata
      - ./enCount:/home/enuser/enCount
    working_dir: /home/enuser/enCount
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo

volumes:
  endata:
    external:
      name: endata_test
  mongodata:
    external:
      name: mongodata_test

