version: '2'
services:
  redis:
    image: redis
    ports:
     - "6379:6379"

  mongo:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - dbdata:/data

  rqdashboard:
    build:
      context: .
      dockerfile: Dockerfile-rqdashboard
    ports:
     - "9181:9181"
    depends_on:
     - redis
    links:
     - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    volumes:
      - .:/home/enuser/enCount
    working_dir: /home/enuser/enCount
    depends_on:
      - redis
      - mongo
      - main
    links:
     - redis
     - mongo
     - main
    volumes:
    - endata:/endata

  main:
    build:
      context: .
      dockerfile: Dockerfile-main
    volumes:
      - .:/home/enuser/enCount
      - endata:/endata
    working_dir: /home/enuser/enCount
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo

volumes:
  endata:
  dbdata:
