version: '2'
services:
  redis:
    image: redis
    ports:
     - "6379:6379"
    command: redis-server --bind 0.0.0.0

  mongo:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - mongodata:/data

  rqdashboard:
    image: encount
    entrypoint:
     - /home/enuser/.encountenv/bin/rq-dashboard
     - -H
     - redis
    ports:
     - "9181:9181"
    depends_on:
     - redis
    links:
     - redis

  worker:
    image: encount
    working_dir: /home/enuser/
    entrypoint:
     - /home/enuser/.encountenv/bin/rqworker
     - --url
     - redis://redis
     - downloads
     - gtfs
     - mappings
     - junctions
    depends_on:
      - redis
      - mongo
      - main
    links:
     - redis
     - mongo
     - main
    volumes:
    - endata:/endata
    - ./enCount:/home/enuser/enCount

  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: encount
    working_dir: /home/enuser/
    volumes:
      - endata:/endata
      - ./enCount:/home/enuser/enCount
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo

volumes:
  endata:
    external:
      name: endata_test
  mongodata:
    external:
      name: mongodata_test

