FROM ubuntu:14.04.4
MAINTAINER Tomaz Curk <tomazc@gmail.com>

# thanks to https://github.com/bschiffthaler/ngs/blob/master/base/Dockerfile
# and https://github.com/AveraSD/ngs-docker-star/blob/master/Dockerfile

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN useradd -u 1010 -m -d /home/enuser enuser

# update system and install prerequisites
# avoid apt-get upgrade -y
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
    wget \
    g++ \
    zlib1g-dev \
    libzmq-dev \
    make \
    python3 \
    python3-pip \
    python3-setuptools \
    python-virtualenv \
    python-pip \
    git

RUN apt-get autoclean -y && \
    apt-get autoremove -y


#################
### RNA-star

# compile STAR from source
WORKDIR /tmp/STAR
RUN wget https://github.com/alexdobin/STAR/archive/STAR_2.4.2a.tar.gz
RUN tar -xvzf STAR_2.4.2a.tar.gz
WORKDIR /tmp/STAR/STAR-STAR_2.4.2a/source
RUN make STAR
RUN mkdir -p /home/enuser/bin && cp STAR /home/enuser/bin
WORKDIR /tmp
RUN rm -rfv STAR


#################
#### enCount
USER enuser
WORKDIR /home/enuser
ADD requirements.txt /home/enuser
RUN virtualenv -p python3 /home/enuser/.encountenv
RUN .encountenv/bin/pip install --upgrade -r requirements.txt

USER root
ADD . /home/enuser/enCount
RUN chown -R enuser.enuser /home/enuser

RUN mkdir /endata
RUN chown -R enuser.enuser /endata

USER enuser
WORKDIR /home/enuser/enCount
RUN ../.encountenv/bin/python setup.py develop

CMD ["/home/enuser/.encountenv/bin/rqworker", "--url", "redis://redis", "downloads", "gtfs"]